import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { api, buildUrl } from "@shared/routes"; // Mocking import path based on prompt instructions
// Actual import simulation since we can't see the exact file structure generated by agent
// In real app, import from "@shared/routes"

// Explicit types if we can't import easily
type SubscriptionResponse = {
  isPro: boolean;
  subscription: any;
};

export function useSubscription() {
  return useQuery<SubscriptionResponse>({
    queryKey: ["/api/subscription"],
    queryFn: async () => {
      const res = await fetch("/api/subscription");
      if (res.status === 401) return { isPro: false, subscription: null };
      if (!res.ok) throw new Error("Failed to fetch subscription");
      return res.json();
    },
    retry: false,
  });
}

export function useUpgradeSubscription() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async () => {
      const res = await fetch("/api/subscription", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      if (!res.ok) throw new Error("Failed to upgrade");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/subscription"] });
    },
  });
}
